### ISSUE TITLE
No native Windows version of cvcuda available

### ISSUE THREAD

**Issue by offmybach** [yondonfu/ComfyUI-Background-Edit#2]
Tried twice to install and both times getting this error...

Traceback (most recent call last):
  File "K:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Edit\__init__.py", line 2, in <module>
    from .nodes.gaussian_blur import GaussianBlur
  File "K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Edit\nodes\gaussian_blur.py", line 2, in <module>
    import cvcuda
ModuleNotFoundError: No module named 'cvcuda'

Cannot import K:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Background-Edit module for custom nodes: No module named 'cvcuda'

**Comment by yondonfu** [comment]
Ah theses nodes are only installed with the Linux version of cvcuda right now and unfortunately based on [this issue](https://github.com/CVCUDA/CV-CUDA/issues/92) it doesn't look like there is a native Windows version available yet. 

I'll take a look at the available paths to supporting Windows and at the very least allowing the nodes to be used in CPU mode if cvcuda can't be installed on the OS, but until then you'll only be able to use these nodes on Linux (either natively or via [WSL](https://learn.microsoft.com/en-us/windows/wsl/install) as mentioned in [this issue](https://github.com/CVCUDA/CV-CUDA/issues/92#issuecomment-1924732354)).

**Comment by yondonfu** [comment]
@offmybach I just pushed a [new release](https://github.com/yondonfu/ComfyUI-Background-Edit/releases/tag/v1.1.0) that should support Windows by replacing the cvcuda dependency. The latest release can be installed from the [Comfy Registry](https://registry.comfy.org/nodes/comfyui-background-edit).

I'll close this as fixed for now, but if you run into any issues feel free to re-open or open another issue.
